### ISSUE TITLE
Error in compiling "pthread.h - no such file or directory" (CB::12.11 and OF 0.8 on Win7)

### ISSUE THREAD

**Issue by amicoleo** [danomatika/ofxPd#33]
Hi, 
I have CB::12.11 and OF 0.8 on a freshly installed Win7 computer. 

ofxPd examples didn't compile because of _pthread.h_ missing. Had a quick research (here too https://github.com/danomatika/ofxPd/issues/new) and had it to compile with this workaround. Not the cleanest solution, but hei! It worked. 

1. Copy _pthread.h_ and _sched.h_ into _MinGW/include_ (I've got the files from here ftp://sourceware.org/pub/pthreads-win32/prebuilt-dll-1-10-0-release/include/)

2. Get _libpthreadGC1.a_ from ftp://sourceware.org/pub/pthreads-win32/prebuilt-dll-1-10-0-release/lib/ rename it to _libpthread.a_ and copy into  _MinGW/lib_

3. Get _pthreadGC1.dll_ again from ftp://sourceware.org/pub/pthreads-win32/prebuilt-dll-1-10-0-release/lib/ and copy it into _MinGW/bin_

**Comment by danomatika** [comment]
This isn't really an issue with ofxPd directly since pthread should be included with CB on Windows. Closing the issue for now.
