### ISSUE TITLE
Project built with the OF project generator and ofxPd doesn't compile out of the box

### ISSUE THREAD

**Issue by alesaccoia** [danomatika/ofxPd#41]
To compile successfully, the pure-data files need to have some definitions: they have been set correctly in the add-on example, and they are defined in addon_config.mk, but using the OF project generator they end up in "Other C++ flags" instead of "Other C Flags"
ADDON_CFLAGS = -DHAVE_UNISTD_H -DUSEAPI_DUMMY -DPD

Is there another line to specify the "Other C Flags" in the addon_config.mk? or is it the project generator making no difference between C++ and C flags and always lumping them as C++ Flags? either way, a project built with the ofxPd addon added to the project generator won't compile out of the box

**Comment by danomatika** [comment]
Ok I fixed this in the PG and the OF makefiles: https://github.com/ofZach/projectGeneratorSimple/pull/62

ofxPD will work with the PG in the next OF release.
