### ISSUE TITLE
trouble building iOS example

### ISSUE THREAD

**Issue by batchku** [danomatika/ofxPd#42]
after some adjustments to to find all dependencies, i'm getting stuck with this error:

/Users/ali/GoogleDrive/Development/of_v0.8.4_ios_release/apps/myApps/example/src/AppCore.h:64:3: No template named 'vector'; did you mean 'std::vector'?

![image](https://cloud.githubusercontent.com/assets/518356/5309914/5c4c079a-7bf9-11e4-84d8-750a872a16df.png)

and this one:

/Users/ali/GoogleDrive/Development/of_v0.8.4_ios_release/apps/myApps/example/src/testApp.cpp:13:10: 'Poco/Path.h' file not found

![image](https://cloud.githubusercontent.com/assets/518356/5309922/66ddf2cc-7bf9-11e4-98e0-e67c87c5d486.png)

**Comment by danomatika** [comment]
Haven't heard anything more. Closing this issue.
