### ISSUE TITLE
no "examples" folder in openFrameworks/addons/ofxPd/example/

### ISSUE THREAD

**Issue by batchku** [danomatika/ofxPd#43]
under "How to Create a New ofxPd Project" in the readme, it says:

To develop your own project based on ofxPd, simply copy the example project and rename it. You probably want to put it in your apps folder, for example, after copying:

openFrameworks/addons/ofxPd/example/ => openFrameworks/apps/myApps/example/

i find that there is no "example" folder in the ofxPd folder.
there's pdExample and pdExampleIOS

ali

**Comment by danomatika** [comment]
The examples are `pdExample`, `pdExampleIOS`, `pitchShifter`, & `pitchShifterIOS`. `example` was the old name which was not updated in the readme. That is fixed now. As per the project files, none of the examples come with existing Xcode, CodeBlocks, etc projects and they can be created using the OF ProjectGenerator. Those instructions assume the example's project files have already been generated before copying the example folder.
