### ISSUE TITLE
Send to pd is being received twice.

### ISSUE THREAD

**Issue by cerupcat** [danomatika/ofxPd#47]
I'm having a hard time tracking down whether this is a ofxPd issue or libpd issue, but I'm doing a sendList to pd and for some reason it's being received twice in the patch. I have a print in libpd showing that it only sends once and a print inside the patch and it's printing twice. Has this been seen before?

**Comment by danomatika** [comment]
Are you manually processing messages? You might be processing *and* having it done automatically.

**Comment by danomatika** [comment]
Also, is it a list being sent to a named receive object or is it being sent via a message box with "; "

**Comment by cerupcat** [comment]
Thanks for the quick reply.

I'm sending like:
```
            List pdList;
            pdList.addSymbol(notes.begin()->second.type);
            pdList.addFloat(notes.begin()->second.note);
            pdList.addFloat(notes.begin()->second.volume);
            pdList.addFloat(notes.begin()->second.pan);
            pd->sendList("PlayList", pdList);   
```

and in PD it's receving using:

[r Playlist]
|
|

**Comment by cerupcat** [comment]
How do I tell if something is happening automatically? Is that something new?

**Comment by danomatika** [comment]
https://github.com/danomatika/ofxPd/blob/master/src/ofxPd.h#L63

**Comment by danomatika** [comment]
Checking pdExample and List sending only prints once.

**Comment by danomatika** [comment]
Do you reuse that list object? You might need to clear it before adding data and sending again since items are appended ...

**Comment by cerupcat** [comment]
Thanks for looking into it. I have queued set to false and from what I can tell that only related to receiving messages inside the app whereas this is an issue with sending.

A new list is created every time it sends and it's always received exactly twice. I'm going to see if it's just lists or all messages in a minute.

This on iOS BTW (not sure if that'll make a difference - it shouldn't).

**Comment by danomatika** [comment]
I check pdExampleIOS and things are fine there too.

**Comment by cerupcat** [comment]
Going to try using my patch in the example project and see what it does. I get a bunch of "multiply defined" warnings in the patch as well which I'm not sure what that's related to and it's related.

**Comment by cerupcat** [comment]
Looked again and turns out I was somehow opening two of the same patch - not what I wanted to do. Thanks again for taking the time - I really appreciate it!

**Comment by danomatika** [comment]
Always check the "examples". They are really just unit tests ;)

**Comment by cerupcat** [comment]
@danomatika Yeah, good point. hah ;)
