### ISSUE TITLE
add ofxPoco to addons.make

### ISSUE THREAD

**Issue by danzeeeman** [danomatika/ofxPd#51]
ofxPoco is a dependency in 0.10+ need to add them to the addons.make files.

**Comment by danomatika** [comment]
Thanks for the info. I'll look into removing Poco dependencies from my adding.

**Comment by danomatika** [comment]
Ok, looks easy. I'll swap the Poco mutex with std::mutex.

**Comment by danzeeeman** [comment]
Word!

**Comment by danomatika** [comment]
Actually I had already removed the Poco mutex and the include was just a left over.
