### ISSUE TITLE
Codeblocks seemingly not being officially supported from of/windows 0.84

### ISSUE THREAD

**Issue by simlei** [danomatika/ofxPd#54]
Since there are no official distributions for codeblocks on windows, could you provide visual studio 2015 compatible instructions, ore any hints on what it would take to make this addon work with a windows machine and the latest releases of openframeworks? anything is much appreciated :)

**Comment by danomatika** [comment]
libpd does not currently build in Visual Studio. One option is to build libpd itself in MinGW and then use the .dll with your open frameworks project. In that case, you only need the src file in the ofxPd folder and not the pd files in libs.

**Comment by simlei** [comment]
Thank you! :)

**Comment by danomatika** [comment]
This is not to say it's *impossible*. Here's the main background: https://github.com/libpd/libpd/issues/86

**Comment by danomatika** [comment]
Closing this for now. See #64.
