### ISSUE TITLE
Loading a huge file onto patch and start dsp at the same time

### ISSUE THREAD

**Issue by chikashimiyama** [danomatika/ofxPd#59]
hi dan,

in my patch I use a lot of tables and load 2GB of sound files to them using soundfiler object when the patch is opened and at the same time I start dsp inside the patch, using ";pd dsp 1" message in a message box connected to a loadbang. It always produces a crash.

```
Mac OS 10.12, of0.9.8, Xcode8
com.apple.audio.IOThread.client EXC_BAD_ACCESS.
```

**Comment by danomatika** [comment]
It's probably taking too long to load in the audio thread and the system is killing the process.

**Comment by chikashimiyama** [comment]
loadbang -> delay 10000 -> pd dsp 1 
solved the problem. thanks.
