### ISSUE TITLE
'system' is unavailable: not available on iOS

### ISSUE THREAD

**Issue by Miles-Tone** [danomatika/ofxPd#63]
With iOS11 out, and with he new files app, system isn't available as a function call anymore, as a work around, building against an older version of iOS in Xcode works, but just wanted to flag this for moving forwards. The issue presents itself in s_file.c

**Comment by danomatika** [comment]
This is well known and a fix will be included with a libpd update. I'm just sure when we'll get to it.

**Comment by Miles-Tone** [comment]
That’s great, thanks Dan! Just thought I would flag just in case!
Thanks again,
Miles

**Comment by danomatika** [comment]
This is now fixed with the latest commits. You will need to regenerate your projects as some files have been removed.
