### ISSUE TITLE
Debug Assertion Failed in Visual Studio 2015

### ISSUE THREAD

**Issue by cuinjune** [danomatika/ofxPd#66]
Hi,I have an app that uses ofxPd and ofxMidi which works fine when I run in Release mode.
However it fails when I build and run the app in Debug mode. 
<img width="979" alt="screen shot 2018-02-02 at 7 07 25 pm" src="https://user-images.githubusercontent.com/24947986/35729816-428c7274-0853-11e8-932d-1bd90794ac29.png">
It builds successfully but fails as soon as I run the app.
I tested this on both 32bit and 64bit app and the results were the same.
I don't have this problem with a plain OF app without any addon used so I'm guessing it has to do with ofxPd or ofxMidi?
Any idea how to fix this?
I tested this on Visual  Studio 2015, Windows 10.

**Comment by danomatika** [comment]
I don't know. A vector<bool> is not used in any of the ofxMidi sources. The only mention of one is in ofFbo.h.

You need to find where the assertion is happening. Can you look at the backtrack and/or use a breakpoint and step through the program until you get the assertion?

**Comment by cuinjune** [comment]
I just tried with the ofxPd's pdExample and the problem no longer happened.
I believe the crash has nothing to do with ofxPd or ofxMidi.
Just figured I used couple vector<bool> variables in my own class. 
I will find a solution and sorry for the inconvenience.
