### ISSUE TITLE
clang error "-mtune=native"

### ISSUE THREAD

**Issue by Jakki12** [danomatika/ofxPd#71]
Hey, 
I am trying to run the pdExampleIOS Project from ofxPd out of Xcode onto my iPhone 6.
I am working out of the ios-zip from openframeworks.cc.
When I try to start the app, I get this error:

clang: error: the clang compiler does not support '-mtune=native'

When I run the project using the simulator for iPhone 6, it works.

When I go to Build Settings >> Custom Compiler Flags and then delete the "-mtune=native"-Flag, the project compiles to my real iPhone successfully. But I don't know if that is a good thing to do.

**Comment by danomatika** [comment]
ofxPD does not request this flag it's addons_config.mk, so this is most likely a problem with OF itself, the project generator, etc and not with ofxPd itself.

**Comment by Jakki12** [comment]
I don‘t know what the flag is for, but you can remove it at Xcode‘s custom compiler flags and then your project should compile.
Best, Jakob
