### ISSUE TITLE
Cannot build pdMultiExample

### ISSUE THREAD

**Issue by cuinjune** [danomatika/ofxPd#76]
When I generate the project using PG, and then build it, I cannot build the project because of the following errors:

<img width="861" alt="Screen Shot 2019-11-26 at 5 53 22 AM" src="https://user-images.githubusercontent.com/24947986/69623622-39e4b600-1011-11ea-95be-12141f99c062.png">

Does ofxPd no longer support multiple pd instance?

**Comment by danomatika** [comment]
Use the libpd wrappers now, ala libpd_new_instance(), libpd_set_instance(), etc. When updating to newer versions and seeing issues like this, check the change log first.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment]
Try latest commit.

**Comment by cuinjune** [comment]
Thank you. I could build it but it makes a weird glitchy noise when I run it.

**Comment by danomatika** [comment]
>I could build it but it makes a weird glitchy noise when I run it.

That's probably because it wasn't built with multiple instance support enabled. I added info about this to the readme: https://github.com/danomatika/ofxPd#pdmultiexample--multiple-instance-support
