### ISSUE TITLE
audioReceived & audioRequested deprecated

### ISSUE THREAD

**Issue by Nejrup** [danomatika/ofxPd#92]
Should pd.audioIn work with `(ofSoundBuffer& buffer)` instead of the deprecated `(float * input, int bufferSize, int nChannels)` ?

& `audioReceived(float * input, int bufferSize, int nChannels)` be replaced replaced with `audioIn(ofSoundBuffer& buffer)` in the examples (+ `audioRequested` -> `audioOut`) ?

Thanks for the great work btw!

**Comment by danomatika** [comment]
Probably. I would just have the ofSoundBuffer versions call the current audioReceived version. No need to replicate the stuff inside.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment]
ofSoundBuffer support is now added in the latest commits. I prefer to keep the original implementations with the raw buffer as a lower level option and not to break old projects.
